apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-cluster-access
  labels:
    app: {{ template "airflow.name" . }}-scheduler
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
